### ISSUE TITLE
Modularize html

### ISSUE THREAD

**Issue by surajdm123** [Himanshuu-Gupta/Simplii#1]
There should be a base html page. All the common features should be reused from that page.

**Comment by surajdm123** [comment]
Reopened issue because more features should be modularised.

**Comment by Ashnayak** [comment]
You can add HTML code for tasks in a separate folder. It'll be easier to maintain the code.

**Comment by surajdm123** [comment]
Yeah, I have done that. Please review it.

**Comment by Ashnayak** [comment]
Saw the code changes. Looks good.
Closing the issue.
