### ISSUE TITLE
Add DB unit tests

### ISSUE THREAD

**Issue by ShreyanshPrajapati** [Himanshuu-Gupta/Simplii#15]
DB unit testing module should test the following operations:
Tables
CRUD operations
Connection with AWS RDS

**Comment by ShreyanshPrajapati** [comment]
@surajdm123 @Himanshuu-Gupta  Please use https://github.com/Himanshuu-Gupta/Simplii/pull/33 for developing unit tests for other components.

**Comment by surajdm123** [comment]
> @surajdm123 @Himanshuu-Gupta Please use #33 for developing unit tests for other components.

Sure, I'll look into it.

**Comment by Himanshuu-Gupta** [comment]
checked the PR #33.
Testcases looks good. Can merge to main
