### ISSUE TITLE
Database schema ER diagram

### ISSUE THREAD

**Issue by ShreyanshPrajapati** [Himanshuu-Gupta/Simplii#21]
Add DB schema in the documentation for future reference

**Comment by surajdm123** [comment]
The proposed DB has to be changed.

**Comment by ShreyanshPrajapati** [comment]
It is addressed in the PR: https://github.com/Himanshuu-Gupta/Simplii/pull/24

**Comment by surajdm123** [comment]
Looks good.
Merging it.
