### ISSUE TITLE
Bug: Add new Task query needs to be updated

### ISSUE THREAD

**Issue by surajdm123** [Himanshuu-Gupta/Simplii#47]

**Comment by surajdm123** [comment]
@Himanshuu-Gupta 
Getting SQL exception. Could you please check what the issue is?

**Comment by Himanshuu-Gupta** [comment]
@surajdm123 
There was an issue with the DB schema. Resolved it now. 
Please check

**Comment by surajdm123** [comment]
Checking

**Comment by surajdm123** [comment]
Seems to be working now. Thank you!
@Sneha-at please fix this bug.
